routes/web.php
<?php

use App\Models\Grade;
use App\Models\Setting;
use App\Models\Teacher;
use Barryvdh\DomPDF\PDF;
use App\Models\ClassRoom;
use App\Models\TimeTable;
use App\Models\AcademicYear;
use App\Models\TimetableSlot;
use App\Models\ClassSubjectModel;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
// use App\Models\Timetable;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\SlotTimeController;
use App\Http\Controllers\ClassRoomController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TimeTableController;
use App\Http\Controllers\FileManagerController;
use App\Http\Controllers\SubjectTypeController;
use App\Http\Controllers\AcademicYearController;
use App\Http\Controllers\ClassSubjectController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TimetableSlotController;

// Route::get('/', function () {
//     return view('welcome');
// });

// change language
Route::get('language/{locale}', function ($locale) {
    app()->setLocale($locale);
    session()->put('locale', $locale);
    $language = \App\Models\Setting::where('type', 'language')->first();
    session()->put('language_settings', $language);
    return redirect()->back();
})->name('change_language');

Route::post('save_temp_file', [FileManagerController::class, 'saveTempFile'])->name('save_temp_file');
Route::get('timetable/timetablepdf/{id}', [FrontController::class, 'timetablepdf'])->name('timetable.timetablepdf');

// Route::get('/', function() {
//     return view('front.index');
// });

Route::group(['middleware' => ['SetFrontSessionData']], function () {
    Route::get('/', [FrontController::class, 'index'])->name('front.index');

    Route::group(['prefix' => 'front', 'as' => 'front.'], function () {
        Route::get('news', [FrontController::class, 'news'])->name('news');
        Route::get('gallery', [FrontController::class, 'gallery'])->name('gallery');
        Route::get('newsdetail/{id}', [FrontController::class, 'newsdetail'])->name('newsdetail');
        Route::get('about', [FrontController::class, 'about'])->name('about');
        Route::get('contact', [FrontController::class, 'contact'])->name('contact');

        Route::get('timetable', [FrontController::class, 'timetable'])->name('timetable');
        Route::get('timetable/{id}/show', [FrontController::class, 'timetableDetail'])->name('timetable.detail');




    });

    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('login', [AuthController::class, 'AuthLogin']);
    Route::get('register', [AuthController::class, 'register'])->name('register');
    Route::post('register', [AuthController::class, 'store']);
    Route::get('logout', [AuthController::class, 'logout']);
    Route::get('forgot-password', [AuthController::class, 'forgotpassword']);
    Route::post('forgot-password', [AuthController::class, 'PostForgotPassword']);
    Route::get('reset/{token}', [AuthController::class, 'reset']);
    Route::post('reset/{token}', [AuthController::class, 'PostReset']);
});



// Route::get('admin/dashboard', function () {
//     return view('admin.dashboard');
// })->name('admin.dashboard');



Route::group(['middleware' => ['admin', 'auth', 'SetSessionData']], function () {

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/dashboard' , [DashboardController::class,'dashboard'])->name('dashboard');
        Route::get('/admin/dashboard', [DashboardController::class, 'dashboard'])->name('admin.dashboard');
        Route::get('/user/profile', [DashboardController::class, 'profile'])->name('user.profile');
        Route::get('/user/profile_edit/{id}', [DashboardController::class, 'edit'])->name('user.profile_edit');
        Route::put('/user/profile_update/{id}', [DashboardController::class, 'update'])->name('user.profile_update');
        // Route::get('admin/user/profile_edit/{id}', [DashboardController::class, 'edit'])->name('admin.user.profile_edit');
        // Route::get('/dashboard', function () {

        //     $data['header_title'] = 'Dashboard';
        //     $classRoomsCount = ClassRoom::count();
        //     // $timetableCount = Timetable::count();
        //     $teachersCount = Teacher::count('id');
        //     return view('admin/dashboard',compact('data','classRoomsCount', 'teachersCount'));
        //     // return view('admin.dashboard');
        // })->name('dashboard');

        Route::get('admin/list', [AdminController::class, 'list'])->name('admin.list');
        Route::get('admin/add', [AdminController::class, 'add']);
        Route::post('admin/add', [AdminController::class, 'insert']);
        Route::get('admin/edit/{id}', [AdminController::class, 'edit']);
        Route::post('admin/edit/{id}', [AdminController::class, 'update']);
        Route::get('admin/delete/{id}', [AdminController::class, 'delete']);


        //change_password
        Route::get('change_password', [UserController::class, 'change_password']);
        Route::post('change_password', [UserController::class, 'update_change_password']);

        //Student
        Route::get('student/list', [StudentController::class, 'list']);
        Route::get('student/add', [StudentController::class, 'add']);
        Route::post('student/add', [StudentController::class, 'insert']);

        Route::get('timetable/welcome', function (){
            return view('admin.timetable.welcome');
        });


        Route::resource('grade', GradeController::class);

        Route::get('class_room/update_is_outstanding', [ClassRoomController::class, 'updateIsOutstanding'])->name('class_room.update_is_outstanding');
        Route::resource('class_room', ClassRoomController::class);

        Route::resource('subject_type', SubjectTypeController::class);

        Route::resource('subject', SubjectController::class);
        Route::get('teacher/loadImportForm',[TeacherController::class,'loadImportForm'])->name('teacher.loadImportForm');
        Route::post('teacher/import',[TeacherController::class,'ImportTeacher'])->name('teacher.import');
        Route::get('teacher/export', [TeacherController::class, 'ExportTeacher'])->name('teacher.export');
        Route::get('teacher/{id}/timetable', [TeacherController::class, 'timetable'])->name('teacher.timetable');
        Route::resource('teacher', TeacherController::class);
        Route::resource('user', UserController::class);

        Route::get('timetable/generate', [TimeTableController::class, 'generateTimetable'])->name('timetable.generate');
        // Route::match(['get', 'post'], 'timetable/show_popup_create',[TimeTableController::class, "showPopupCreate"])->name('timetable.showPopupCreate');
        Route::get('timetable/show_popup_create',[TimeTableController::class, "showPopupCreate"])->name('timetable.showPopupCreate');
        Route::get('timetable/{id}/show_popup_edit',[TimeTableController::class, "showPopupEdit"])->name('timetable.showPopupEdit');
        // Route::get('timetable/create_slot',[TimeTableController::class, "showPopupCreate"])->name('timetable.create_slot');
        Route::get('timetable/create_academic_year',[TimeTableController::class, "academicYearCreate"])->name('timetable.academicYearCreate');
        Route::get('timetable/grade_list', [TimeTableController::class, 'getGradeList'])->name('timetable.grade_list');
        Route::post('timetable_slot', [TimetableSlotController::class, 'store'])->name('timetable_slot.store');
        Route::put('timetable_slot/{id}/update', [TimetableSlotController::class, 'update'])->name('timetable_slot.update');
        Route::get('timetable/{id}/adjustment', [TimeTableController::class, 'adjustment'])->name('timetable.adjustment');
        Route::get('timetable/{id}/weekly_adjustment', [TimeTableController::class, 'weeklyAdjustment'])->name('timetable.weekly_adjustment');
        Route::get('timetable_slot/{id}/popup_confirm', [TimetableSlotController::class, 'popupConfirm'])->name('timetable_slot.popupConfirm');
        Route::resource('timetable', TimeTableController::class);


        Route::resource('academic_year', AcademicYearController::class);

        //time_slot
        Route::resource('time_slot', SlotTimeController::class);

        Route::resource('roles', RoleController::class);

        // settings
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {

            Route::get('/', [SettingController::class, 'index'])->name('index');
            Route::put('/save', [SettingController::class, 'save'])->name('save');

            Route::get('/general', [SettingController::class, 'general'])->name('general.index');
            Route::put('/general/save', [SettingController::class, 'generalSave'])->name('general.save');

            // language setup
            Route::group(['prefix' => 'language', 'as' => 'language.'], function () {
                Route::get('/', [LanguageController::class, 'index'])->name('index');
                Route::get('/create', [LanguageController::class, 'create'])->name('create');
                Route::post('/', [LanguageController::class, 'store'])->name('store');
                Route::get('/edit', [LanguageController::class, 'edit'])->name('edit');
                Route::put('/update', [LanguageController::class, 'update'])->name('update');
                Route::delete('delete/', [LanguageController::class, 'delete'])->name('delete');

resources/views/admin/timetable/partials/_class_rooms.blade.php
<div class="tab-pane class-rooms-wrapper" id="tab_1">
    <div class="row">
        {{-- @dd($class_rooms->pluck('name', 'id')) --}}
        @foreach ($class_rooms as $room)
            <div class="col-sm-3">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title font-weight-bold">
                            {{ __('Class') }} {{ $room->name ?? null }}</h5>
                    </div>
                    <div class="card-footer btn-group d-flex justify-content-center"
                        role="group">
                        @php
                            $timetable_id = 0;
                            if (($room->timetables)->isNotEmpty()) {
                                $timetable = $room->timetables->where('academic_year_id', request('academic_year_id'))->first();
                                // dd($timetable);
                                $timetable_id = $timetable->id ?? 0;
                            }
                        @endphp
                        {{-- @dd($timetable_id) --}}
                        <a href="{{ route('admin.timetable.show', $timetable_id) . '?academic_year_id=' . request('academic_year_id') . '&grade_id=' . $grade_id . '&class_id=' . $room->id }}" class="btn btn-primary">{{ __('View') }}</a>

                        <a href="{{ route('admin.timetable.create', [
                            'academic_year_id' => request('academic_year_id'),
                            'grade_id' => $grade_id,
                            'class_id' => $room->id,
                        ]) }}"
                            class="btn btn-danger">{{ __('Create') }}</a>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
</div>

resources/views/admin/timetable/partials/_comfirm_switch_teacher_modal.blade.php
<div class="modal-dialog modal-dialog-centered">
    <form action="{{ route('admin.timetable_slot.update', $timetable_slot->id) }}" method="POST" class="comfirm_form">
        @csrf
        @method('PUT')
        <div class="modal-content">
            <div class="modal-header" style="border-bottom: none">
            </div>
            <div class="modal-body">
                <input type="hidden" name="is_confirmed" value="1">
                @if ($switch_teacher_input)
                    <input type="hidden" name="academic_year_id" value="{{ $switch_teacher_input['academic_year_id'] }}">
                    <input type="hidden" name="grade_id" value="{{ $switch_teacher_input['grade_id'] }}">
                    <input type="hidden" name="class_id" value="{{ $switch_teacher_input['class_id'] }}">
                    <input type="hidden" name="week_day" value="{{ $switch_teacher_input['week_day'] }}">
                    <input type="hidden" name="time_slot" value="{{ $switch_teacher_input['time_slot'] }}">
                    <input type="hidden" name="subject" value="{{ $switch_teacher_input['subject'] }}">
                    <input type="hidden" name="teacher" value="{{ $switch_teacher_input['teacher'] }}">

                @endif
                <div class="text-center mb-3">
                    <img src="{{ asset('images/switch-teacher.png') }}" alt="switch-teacher" width="70px">
                </div>
                <h3 class="text-center">{{ __('Are you sure ?') }}</h3>
                <p class="text-center" style="font-size: 1.1rem">
                    <span>
                        {{ __('The select teacher is not available') }}
                    </span>
                    <br>
                    <span>
                        {{ __('Click "CONTINUE" to swith current teacher with the selected teacher') }}
                    </span>
                </p>
            </div>
            <div class="modal-footer justify-content-center">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('CANCEL') }}</button>
                <button type="submit" class="btn btn-primary submit">{{ __('CONTINUE') }}</button>
            </div>
        </div>
    </form>
</div>

{{-- @push('script') --}}
    <script>
        $('.submit').click(function (e) {
            e.preventDefault();
            var data = $('.comfirm_form').serialize();
            $.ajax({
                type: "post",
                url: `{{ route('admin.timetable_slot.update', $timetable_slot->id) }}`,
                data: data,
                success: function (response) {
                    console.log(response);
                    if (response.errors) {
                        for (var i = 0; i < response.errors.length; i++) {
                            Toast.fire({
                                icon: 'error',
                                title: response.errors[i].message,
                            });
                        }
                    } else {
                        Toast.fire({
                            icon: 'success',
                            title: `{{ __('Updated successfully') }}`,
                            // message: ,
                        });

                        $('div.modal_comfirm').modal('hide');
                        // $('.table-wrapper').replaceWith(response.view);
                        $(`#${response.id}`).replaceWith(response.view);
                        // $('.total-count').html(response.total);
                    }

                }
            });
        });
    </script>
{{-- @endpush --}}

resources/views/admin/timetable/partials/_create.blade.php
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ __('Add Timetable') }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        <form action="{{ route('admin.subject_type.store') }}" class="submit-form" method="post">
            <div class="modal-body">
                @csrf
                <input type="hidden" name="academic_year_id" value="{{ $academic_year_id }}">
                <input type="hidden" name="grade_id" value="{{ $grade_id }}">
                <input type="hidden" name="class_id" value="{{ $class_id }}">
                <input type="hidden" name="week_day" value="{{ $week_day }}">
                <input type="hidden" name="time_slot" value="{{ $time_slot }}">
                <div class="form-group">
                    <label for="subject">{{ __('Subject') }}</label>
                    <select name="subject" id="subject" class="form-control select2-modal subject_select" style="width: 100%">
                        <option value="" selected disabled>{{ __('Select Suject') }}</option>
                        @foreach ($subjects as $id => $subject)
                            <option value="{{ $id }}">{{ $subject }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="teacher">{{ __('Teacher') }}</label>
                    @include('admin.timetable.partials._teacher_select')
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Close') }}</button>
                <button type="submit" class="btn btn-primary submit">{{ __('Save') }}</button>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.select2-modal').select2({
            theme: 'bootstrap4',
            dropdownParent: $('.modal_form')
        });
    });

    $(document).on('change', '.subject_select', function(e) {
        e.preventDefault();
        var subject_id = $(this).val();
        $.ajax({
            type: "get",
            url: window.location.href,
            data: {
                'subject_id' : subject_id
            },
            dataType: "json",
            success: function (response) {
                if (response.view) {
                    $('.teacher_select_wrapper').replaceWith(response.view);
                    $('.select2-modal').select2({
                        theme: 'bootstrap4',
                        dropdownParent: $('.modal_form')
                    });
                }
            }
        });
    });

    $('.submit').click(function (e) {
        e.preventDefault();
        var data = $('.submit-form').serialize();
        console.log(data);
        $.ajax({
            type: "post",
            url: `{{ route('admin.timetable_slot.store') }}`,
            data: data,
            success: function (response) {
                console.log(response)
                if (response.errors) {
                    for (var i = 0; i < response.errors.length; i++) {
                        Toast.fire({
                            icon: 'error',
                            title: response.errors[i].message,
                        });
                    }
                } else {
                    if (response.status == 'teacher_limit_warning') {
                        Confirmation.fire({
                            title: '{{ __("This teacher has reach the limit teach hour") }}',
                            text: "{{ __('Do you want to continue') }}",
                            icon: 'warning',
                            showCancelButton: true,
                            confirmButtonText: 'Continue',
                            cancelButtonText: 'No, cancel',
                            reverseButtons: true
                        }).then((result) => {
                            if (result.isConfirmed) {
                                data = $('.submit-form').serialize() + '&ignore_teacher_limit=1';
                                console.log(data);
                                $.ajax({
                                    type: "post",
                                    url: `{{ route('admin.timetable_slot.store') }}`,
                                    data: data,
                                    success: function (response) {
                                        if (response.errors) {
                                            for (var i = 0; i < response.errors.length; i++) {
                                                Toast.fire({
                                                    icon: 'error',
                                                    title: response.errors[i].message,
                                                });
                                            }
                                        } else {
                                            Toast.fire({
                                                icon: 'success',
                                                title: `{{ __('Created successfully') }}`,
                                                // message: ,
                                            });
                                        }

                                        $('div.modal_form').modal('hide');
                                        // $('.table-wrapper').replaceWith(response.view);
                                        $(`#${response.id}`).replaceWith(response.view);

                                    }
                                });
                            }
                        });
                    } else {
                        Toast.fire({
                            icon: 'success',
                            title: `{{ __('Updated successfully') }}`,
                            // message: ,
                        });
                    }

                    $('div.modal_form').modal('hide');
                    // $('.table-wrapper').replaceWith(response.view);
                    $(`#${response.id}`).replaceWith(response.view);
                    // $('.total-count').html(response.total);

                }

            }
        });
    });
</script>

resources/views/admin/timetable/partials/_edit.blade.php
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ __('Update Timetable') }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        <form action="{{ route('admin.timetable_slot.update', $timetable_slot->id) }}" class="submit-form" method="post">
            <div class="modal-body">
                @csrf
                @method('PUT')
                <input type="hidden" name="academic_year_id" value="{{ $academic_year_id }}">
                <input type="hidden" name="grade_id" value="{{ $grade_id }}">
                <input type="hidden" name="class_id" value="{{ $class_id }}">
                <input type="hidden" name="week_day" value="{{ $week_day }}">
                <input type="hidden" name="time_slot" value="{{ $time_slot }}">
                @if ($is_adjust == 1)
                    <input type="hidden" name="is_adjust" value="1">
                @endif
                <div class="form-group">
                    <label for="subject">{{ __('Subject') }}</label>
                    <select name="subject" id="subject" class="form-control select2-modal subject_select" style="width: 100%">
                        <option value="" selected disabled>{{ __('Select Suject') }}</option>
                        @foreach ($subjects as $id => $subject)
                            <option value="{{ $id }}" @if($id == $timetable_slot->subject_id) selected @endif>{{ $subject }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="teacher">{{ __('Teacher') }}</label>
                    @include('admin.timetable.partials._teacher_select')
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Close') }}</button>
                <button type="submit" class="btn btn-primary submit">{{ __('Save') }}</button>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.select2-modal').select2({
            theme: 'bootstrap4',
            dropdownParent: $('.modal_form')
        });
    });

    $(document).on('change', '.subject_select', function(e) {
        e.preventDefault();
        var subject_id = $(this).val();
        $.ajax({
            type: "get",
            url: window.location.href,
            data: {
                'subject_id' : subject_id
            },
            dataType: "json",
            success: function (response) {
                if (response.view) {
                    $('.teacher_select_wrapper').replaceWith(response.view);
                    $('.select2-modal').select2({
                        theme: 'bootstrap4',
                        dropdownParent: $('.modal_form')
                    });
                }
            }
        });
    });

    $('.submit').click(function (e) {
        e.preventDefault();
        var data = $('.submit-form').serialize();
        $.ajax({
            type: "post",
            url: `{{ route('admin.timetable_slot.update', $timetable_slot->id) }}`,
            data: data,
            success: function (response) {
                console.log(response);
                if (response.errors) {
                    for (var i = 0; i < response.errors.length; i++) {
                        Toast.fire({
                            icon: 'error',
                            title: response.errors[i].message,
                        });
                    }
                } else if (response.status == 'adjustment_warning') {
                    $('div.modal_form').modal('hide');
                    $("div.modal_comfirm").load(response.href, function() {

                        $('div.modal_comfirm').modal('show');

                    });
                } else {
                    Toast.fire({
                        icon: 'success',
                        title: `{{ __('Created successfully') }}`,
                        // message: ,
                    });

                    $('div.modal_form').modal('hide');
                    // $('.table-wrapper').replaceWith(response.view);
                    $(`#${response.id}`).replaceWith(response.view);
                    // $('.total-count').html(response.total);
                }

            }
        });
    });
</script>

resources/views/admin/timetable/partials/_table.blade.php
<div class="card-body p-0 table-wrapper">
    <table class="table table-striped">
        <thead>
            <tr>
                {{-- <th >#</th> --}}
                <th>{{ __('Name') }}</th>
                {{-- <th>Created by</th> --}}
                <th>{{ __('Created date') }}</th>
                <th>{{ __('Action') }}</th>
            </tr>
        </thead>
        <tbody>
            {{-- @foreach ($academicyears as $academicyear)
                <tr>
                
                    <td>{{$academicyear->name}}</td>
                    <td>{{ $academicyear->created_at->format('d M Y h:i A') }}</td>
                    <td>
                        <a href="#" data-href="{{ route('admin.timetable.edit', $academicyear->id) }}" data-container=".modal_form" class="btn btn-info btn-sm btn-edit">
                            <i class="fas fa-pencil-alt"></i>
                            {{ __('Edit') }}
                        </a>

                        <form action="{{ route('admin.timetable.destroy', $academicyear->id) }}" class="d-inline-block form-delete-{{ $academicyear->id }}">
                            @csrf
                            @method('DELETE')
                            <button type="submit" data-id="{{ $academicyear->id }}" data-href="{{ route('admin.timetable.destroy', $academicyear->id) }}" class="btn btn-danger btn-sm btn-delete">
                                <i class="fas fa-trash"></i>
                                {{ __('Delete') }}
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach --}}
        </tbody>
    </table>
    {{-- <div style="padding: 10px; float: right;">

        {{ $grades->links() }}
    </div> --}}

    <div class="row">
        <div class="col-12 d-flex flex-row flex-wrap">
            {{-- <div class="row" style="width: -webkit-fill-available;">
                <div class="col-12 col-sm-6 text-center text-sm-left pl-3" style="margin-block: 20px">
                    {{ __('Showing') }} {{ $academicyears->firstItem() }} {{ __('to') }} {{ $academicyears->lastItem() }} {{ __('of') }} {{ $academicyears->total() }} {{ __('entries') }}
                </div>
                <div class="col-12 col-sm-6 pagination-nav pr-3"> {{ $academicyears->links() }}</div>
            </div> --}}
        </div>
    </div>


</div>

resources/views/admin/timetable/partials/_teacher_select.blade.php
<div class="teacher_select_wrapper">
    <select name="teacher" id="teacher" class="form-control select2-modal teacher_select" style="width: 100%">
        <option value="" selected disabled>{{ __('Select Teacher') }}</option>
        @foreach ($teachers as $id => $teacher)
            <option value="{{ $id }}" @if(isset($timetable_slot) && $id == $timetable_slot->teacher_id) selected @endif>{{ $teacher }}</option>
        @endforeach
    </select>
</div>

resources/views/admin/timetable/partials/_timetable_slot.blade.php
<td class="text-center position-relative timetble-slot-td" id="{{ $day . '-' . $time_id }}">
    <input type="hidden" name="week_day" class="week_day" value="{{ $day }}">
    <input type="hidden" name="time_slots" class="time_slot" value="{{ $time_id }}">

    <span class=" text-bold">{{ $timetable_slot->subject->name }}</span>
        <br>
        {{ $timetable_slot->teacher->full_name }}
        <a class="btn btn-edit-timetable-slot btn-outline-primary btn-modal d-none" href="#"
            data-href="{{ trim(route('admin.timetable.showPopupEdit', $timetable_slot->id)) }}"
            data-toggle="modal" data-container=".modal_form">
            <span>
                {{ __('Edit') }}
            </span>
        </a>

    {{-- <a class="btn btn-outline-success btn-modal rounded-circle btn_circle" href="#"
        data-href="{{ trim(@$timetable_slot ? route('admin.timetable.showPopupEdit', $timetable_slot->id) : route('admin.timetable.showPopupCreate')) }}"
        data-toggle="modal" data-container=".modal_form">
        <i class=" fa fa-pencil-alt"></i>
    </a> --}}
</td>