routes/web.php
<?php

use App\Models\Grade;
use App\Models\Setting;
use App\Models\Teacher;
use Barryvdh\DomPDF\PDF;
use App\Models\ClassRoom;
use App\Models\TimeTable;
use App\Models\AcademicYear;
use App\Models\TimetableSlot;
use App\Models\ClassSubjectModel;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
// use App\Models\Timetable;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\SlotTimeController;
use App\Http\Controllers\ClassRoomController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TimeTableController;
use App\Http\Controllers\FileManagerController;
use App\Http\Controllers\SubjectTypeController;
use App\Http\Controllers\AcademicYearController;
use App\Http\Controllers\ClassSubjectController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TimetableSlotController;

// Route::get('/', function () {
//     return view('welcome');
// });

// change language
Route::get('language/{locale}', function ($locale) {
    app()->setLocale($locale);
    session()->put('locale', $locale);
    $language = \App\Models\Setting::where('type', 'language')->first();
    session()->put('language_settings', $language);
    return redirect()->back();
})->name('change_language');

Route::post('save_temp_file', [FileManagerController::class, 'saveTempFile'])->name('save_temp_file');
Route::get('timetable/timetablepdf/{id}', [FrontController::class, 'timetablepdf'])->name('timetable.timetablepdf');

// Route::get('/', function() {
//     return view('front.index');
// });

Route::group(['middleware' => ['SetFrontSessionData']], function () {
    Route::get('/', [FrontController::class, 'index'])->name('front.index');

    Route::group(['prefix' => 'front', 'as' => 'front.'], function () {
        Route::get('news', [FrontController::class, 'news'])->name('news');
        Route::get('gallery', [FrontController::class, 'gallery'])->name('gallery');
        Route::get('newsdetail/{id}', [FrontController::class, 'newsdetail'])->name('newsdetail');
        Route::get('about', [FrontController::class, 'about'])->name('about');
        Route::get('contact', [FrontController::class, 'contact'])->name('contact');

        Route::get('timetable', [FrontController::class, 'timetable'])->name('timetable');
        Route::get('timetable/{id}/show', [FrontController::class, 'timetableDetail'])->name('timetable.detail');




    });

    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('login', [AuthController::class, 'AuthLogin']);
    Route::get('register', [AuthController::class, 'register'])->name('register');
    Route::post('register', [AuthController::class, 'store']);
    Route::get('logout', [AuthController::class, 'logout']);
    Route::get('forgot-password', [AuthController::class, 'forgotpassword']);
    Route::post('forgot-password', [AuthController::class, 'PostForgotPassword']);
    Route::get('reset/{token}', [AuthController::class, 'reset']);
    Route::post('reset/{token}', [AuthController::class, 'PostReset']);
});



// Route::get('admin/dashboard', function () {
//     return view('admin.dashboard');
// })->name('admin.dashboard');



Route::group(['middleware' => ['admin', 'auth', 'SetSessionData']], function () {

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/dashboard' , [DashboardController::class,'dashboard'])->name('dashboard');
        Route::get('/admin/dashboard', [DashboardController::class, 'dashboard'])->name('admin.dashboard');
        Route::get('/user/profile', [DashboardController::class, 'profile'])->name('user.profile');
        Route::get('/user/profile_edit/{id}', [DashboardController::class, 'edit'])->name('user.profile_edit');
        Route::put('/user/profile_update/{id}', [DashboardController::class, 'update'])->name('user.profile_update');
        // Route::get('admin/user/profile_edit/{id}', [DashboardController::class, 'edit'])->name('admin.user.profile_edit');
        // Route::get('/dashboard', function () {

        //     $data['header_title'] = 'Dashboard';
        //     $classRoomsCount = ClassRoom::count();
        //     // $timetableCount = Timetable::count();
        //     $teachersCount = Teacher::count('id');
        //     return view('admin/dashboard',compact('data','classRoomsCount', 'teachersCount'));
        //     // return view('admin.dashboard');
        // })->name('dashboard');

        Route::get('admin/list', [AdminController::class, 'list'])->name('admin.list');
        Route::get('admin/add', [AdminController::class, 'add']);
        Route::post('admin/add', [AdminController::class, 'insert']);
        Route::get('admin/edit/{id}', [AdminController::class, 'edit']);
        Route::post('admin/edit/{id}', [AdminController::class, 'update']);
        Route::get('admin/delete/{id}', [AdminController::class, 'delete']);


        //change_password
        Route::get('change_password', [UserController::class, 'change_password']);
        Route::post('change_password', [UserController::class, 'update_change_password']);

        //Student
        Route::get('student/list', [StudentController::class, 'list']);
        Route::get('student/add', [StudentController::class, 'add']);
        Route::post('student/add', [StudentController::class, 'insert']);

        Route::get('timetable/welcome', function (){
            return view('admin.timetable.welcome');
        });


        Route::resource('grade', GradeController::class);

        Route::get('class_room/update_is_outstanding', [ClassRoomController::class, 'updateIsOutstanding'])->name('class_room.update_is_outstanding');
        Route::resource('class_room', ClassRoomController::class);

        Route::resource('subject_type', SubjectTypeController::class);

        Route::resource('subject', SubjectController::class);
        Route::get('teacher/loadImportForm',[TeacherController::class,'loadImportForm'])->name('teacher.loadImportForm');
        Route::post('teacher/import',[TeacherController::class,'ImportTeacher'])->name('teacher.import');
        Route::get('teacher/export', [TeacherController::class, 'ExportTeacher'])->name('teacher.export');
        Route::get('teacher/{id}/timetable', [TeacherController::class, 'timetable'])->name('teacher.timetable');
        Route::resource('teacher', TeacherController::class);
        Route::resource('user', UserController::class);

        Route::get('timetable/generate', [TimeTableController::class, 'generateTimetable'])->name('timetable.generate');
        // Route::match(['get', 'post'], 'timetable/show_popup_create',[TimeTableController::class, "showPopupCreate"])->name('timetable.showPopupCreate');
        Route::get('timetable/show_popup_create',[TimeTableController::class, "showPopupCreate"])->name('timetable.showPopupCreate');
        Route::get('timetable/{id}/show_popup_edit',[TimeTableController::class, "showPopupEdit"])->name('timetable.showPopupEdit');
        // Route::get('timetable/create_slot',[TimeTableController::class, "showPopupCreate"])->name('timetable.create_slot');
        Route::get('timetable/create_academic_year',[TimeTableController::class, "academicYearCreate"])->name('timetable.academicYearCreate');
        Route::get('timetable/grade_list', [TimeTableController::class, 'getGradeList'])->name('timetable.grade_list');
        Route::post('timetable_slot', [TimetableSlotController::class, 'store'])->name('timetable_slot.store');
        Route::put('timetable_slot/{id}/update', [TimetableSlotController::class, 'update'])->name('timetable_slot.update');
        Route::get('timetable/{id}/adjustment', [TimeTableController::class, 'adjustment'])->name('timetable.adjustment');
        Route::get('timetable/{id}/weekly_adjustment', [TimeTableController::class, 'weeklyAdjustment'])->name('timetable.weekly_adjustment');
        Route::get('timetable_slot/{id}/popup_confirm', [TimetableSlotController::class, 'popupConfirm'])->name('timetable_slot.popupConfirm');
        Route::resource('timetable', TimeTableController::class);


        Route::resource('academic_year', AcademicYearController::class);

        //time_slot
        Route::resource('time_slot', SlotTimeController::class);

        Route::resource('roles', RoleController::class);

        // settings
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {

            Route::get('/', [SettingController::class, 'index'])->name('index');
            Route::put('/save', [SettingController::class, 'save'])->name('save');

            Route::get('/general', [SettingController::class, 'general'])->name('general.index');
            Route::put('/general/save', [SettingController::class, 'generalSave'])->name('general.save');

            // language setup
            Route::group(['prefix' => 'language', 'as' => 'language.'], function () {
                Route::get('/', [LanguageController::class, 'index'])->name('index');
                Route::get('/create', [LanguageController::class, 'create'])->name('create');
                Route::post('/', [LanguageController::class, 'store'])->name('store');
                Route::get('/edit', [LanguageController::class, 'edit'])->name('edit');
                Route::put('/update', [LanguageController::class, 'update'])->name('update');
                Route::delete('delete/', [LanguageController::class, 'delete'])->name('delete');

resources/views/admin/dashboard.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">{{ __('Dashboard') }}</h1>
                    </div>

                </div>
            </div>
        </section>

        <section class="content">
            <div class="container-fluid">

                <!-- Small boxes (Stat box) -->
                <div class="row">

                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-white">
                            <div class="icon">
                                <div class="widget-icon rounded-circle position-absolute text-info">
                                    <span>
                                        <img src="{{ asset('images/teacher_icon.png') }}" width="100%" height="100%"
                                            style="object-fit: cover">
                                    </span>

                                </div>

                            </div>
                            <div class="inner">
                                <h3>{{ $teachersCount }}</h3>
                                <p>{{ __('Teacher') }}</p>
                                <a href="{{ route('admin.teacher.index') }}"><span>{{__('Show all')}}</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-white">
                            <div class="icon">
                                <div class="widget-icon rounded-circle position-absolute text-info">
                                    <img src="{{ asset('images/academic.png') }}" width="100%" height="100%"
                                        style="object-fit: cover">
                                </div>
                            </div>
                            <div class="inner">
                                <h3>{{ $academicyearsCount }}</h3>
                                <p>{{ __('Academic Year') }}</p>
                                <a href="{{ route('admin.academic_year.index') }}"><span>{{__('Show all')}}</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-white">
                            <div class="icon">
                                <div class="widget-icon rounded-circle position-absolute text-info">
                                    <img src="{{ asset('images/classroom.png') }}" width="100%" height="100%"
                                        style="object-fit: cover">
                                </div>
                            </div>
                            <div class="inner">
                                <h3>{{ $classRoomsCount }}</h3>
                                <p>{{ __('Class Room') }}</p>
                                <a href="{{ route('admin.class_room.index') }}"><span>{{__('Show all')}}</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-white">
                            <div class="icon">
                                <div class="widget-icon rounded-circle position-absolute text-info">
                                    <img src="{{ asset('images/timetable.png') }}" width="100%" height="100%"
                                        style="object-fit: cover">
                                </div>
                            </div>
                            <div class="inner">
                                <h3>{{ $timetableCount }}</h3>
                                <p>{{ __('Timetable') }}</p>
                                <a href="{{ route('admin.timetable.index') }}"><span>{{__('Show all')}}</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 d-flex">
                        <div class="card flex-fill">
                            {{-- <div class="card-header">
                                <div class="row align-items-center">
                                    <div class="col-auto">
                                        <div class="page-title">
                                            <h5>Users Report</h5>
                                        </div>
                                    </div>
                                </div>
                            </div> --}}
                            <div class="card-body">
                                <div id="user-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 d-flex">
                        <div class="card flex-fill">
                            <div class="card-body">
                                <div id="comparison-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 d-flex">
                        <div class="card flex-fill">
                            {{-- <div class="card-header">
                                <div class="row align-items-center">
                                    <div class="col-auto">
                                        <div class="page-title">
                                            <h5>Teacher Report</h5>
                                        </div>
                                    </div>
                                </div>
                            </div> --}}
                            <div class="card-body">
                                <div id="teacher-chart"></div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </section>
    </div>

    @push('script')
        <!-- Include Highcharts library -->
        <script src="https://code.highcharts.com/highcharts.js"></script>
        <script src="https://code.highcharts.com/modules/exporting.js"></script>
        <script src="https://code.highcharts.com/modules/export-data.js"></script>
        <script src="https://code.highcharts.com/modules/accessibility.js"></script>
        <script type="text/javascript">
            var userData = @json($userData);
            var allYears = @json($allYears);
            var teacherSeries = @json($teacherSeries);
            var teacherLabels = @json($teacherLabels);
            var selectedYear;
            var timetableCount = <?= $timetableCount ?>;
            var classRoomsCount = <?= $classRoomsCount ?>;
            var difference = classRoomsCount - timetableCount;
            
            var userChart = Highcharts.chart('user-chart', {
                chart: {
                    type: 'column'
                },
                title: {
                    text: "{{ __('Total Users') }}"
                },
                // subtitle: {
                //     text:
                //         'Source: <a target="_blank" ' +
                //         'href="https://www.indexmundi.com/agriculture/?commodity=corn">indexmundi</a>',
                //     align: 'left'
                // },
                xAxis: {
                    categories: ['{{__('January')}}', '{{__('February')}}', '{{__('March')}}', '{{__('April')}}', '{{__('May')}}', '{{__('June')}}', '{{__('July')}}', '{{__('August')}}', '{{__('September')}}',
                        '{{__('October')}}', '{{__('November')}}', '{{__('December')}}'
                    ],
                    crosshair: true,
                    accessibility: {
                        description: 'Countries'
                    }
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: '{{__('Number of New Users')}}'
                    }
                },
                tooltip: {
                    valueSuffix: ' users'
                },
                plotOptions:     {
                    column: {
                        pointPadding: 0.2,
                        borderWidth: 0
                    }
                },
                series: [{
                    name: '{{__('New users')}}',
                    data: <?php echo json_encode($userSeries); ?>
                }, ],
            });


            // Create teacher chart
            var teacherChart = Highcharts.chart('teacher-chart', {
                chart: {
                    type: 'areaspline',
                    scrollablePlotArea: {
                        minWidth: 600,
                        scrollPositionX: 1
                    }
                },
                title: {
                    text: "{{ __('Total Teacher') }}"
                },
                // subtitle: {
                //     text:
                //         'Source: <a target="_blank" ' +
                //         'href="https://www.indexmundi.com/agriculture/?commodity=corn">indexmundi</a>',
                //     align: 'left'
                // },
                xAxis: {
                    categories: <?php echo json_encode(array_keys($teacherSeries)); ?>,
                    // crosshair: true,
                    accessibility: {
                        description: 'Teacher'
                    }
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: '{{__('Number of Teacher')}}'
                    }
                },
                // tooltip: {
                //     valueSuffix: ' Teachers'
                // },
                plotOptions:     {
                    areaspline: {
                        color: '#7a51be',
                        fillColor: {
                            linearGradient: { x1: 0, x2: 0, y1: 0, y2: 1 },
                            stops: [
                                [0, '#7B51BECF'],
                                [1, '#002eff1f']
                            ]
                        },
                        threshold: null,
                        marker: {
                            enabled: false
                            // lineWidth: 1,
                            // lineColor: null,
                            // fillColor: 'white'
                        }
                    }
                },
                series: [{
                    name: '{{__ ('Total Teachers')}}',
                    data: <?php echo json_encode(array_values($teacherSeries)); ?>
                }, ],
            });
            
            
            Highcharts.chart('comparison-chart', {
                chart: {
                    type: 'pie'
                },
                title: {
                    text: "{{ __('Complete Timetables') }}"
                },
                series: [{
                    name: 'Total',
                    data: [{
                            name: '{{__('Completed')}}',
                            y: timetableCount
                        },
                        // {
                        //     name: 'Class Rooms',
                        //     y: classRoomsCount - difference // Adjust classRoomsCount to show the difference
                        // },
                        {
                            name: '{{__('Pending')}}',
                            y: difference,
                            color: 'gray' // Adjust color as needed
                        }
                    ]
                }],
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.y} ({point.percentage:.1f}%)'
                        }
                    }
                },
                credits: {
                    enabled: false
                },
                exporting: {
                    enabled: true
                }
            });
            // Function to update the chart title based on the selected year
            function updateChartTitle(year) {
                selectedYear = year;

                // Update user chart title
                userChart.setTitle({
                    text: 'New User Growth, ' + (selectedYear ? selectedYear : 'All Years')
                });

                // Update teacher chart title
                teacherChart.setTitle({
                    text: 'Teacher Growth, ' + (selectedYear ? selectedYear : 'All Years')
                });
            }
        </script>
    @endpush
@endsection