routes/web.php
<?php

use App\Models\Grade;
use App\Models\Setting;
use App\Models\Teacher;
use Barryvdh\DomPDF\PDF;
use App\Models\ClassRoom;
use App\Models\TimeTable;
use App\Models\AcademicYear;
use App\Models\TimetableSlot;
use App\Models\ClassSubjectModel;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
// use App\Models\Timetable;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\SlotTimeController;
use App\Http\Controllers\ClassRoomController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TimeTableController;
use App\Http\Controllers\FileManagerController;
use App\Http\Controllers\SubjectTypeController;
use App\Http\Controllers\AcademicYearController;
use App\Http\Controllers\ClassSubjectController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TimetableSlotController;

// Route::get('/', function () {
//     return view('welcome');
// });

// change language
Route::get('language/{locale}', function ($locale) {
    app()->setLocale($locale);
    session()->put('locale', $locale);
    $language = \App\Models\Setting::where('type', 'language')->first();
    session()->put('language_settings', $language);
    return redirect()->back();
})->name('change_language');

Route::post('save_temp_file', [FileManagerController::class, 'saveTempFile'])->name('save_temp_file');
Route::get('timetable/timetablepdf/{id}', [FrontController::class, 'timetablepdf'])->name('timetable.timetablepdf');

// Route::get('/', function() {
//     return view('front.index');
// });

Route::group(['middleware' => ['SetFrontSessionData']], function () {
    Route::get('/', [FrontController::class, 'index'])->name('front.index');

    Route::group(['prefix' => 'front', 'as' => 'front.'], function () {
        Route::get('news', [FrontController::class, 'news'])->name('news');
        Route::get('gallery', [FrontController::class, 'gallery'])->name('gallery');
        Route::get('newsdetail/{id}', [FrontController::class, 'newsdetail'])->name('newsdetail');
        Route::get('about', [FrontController::class, 'about'])->name('about');
        Route::get('contact', [FrontController::class, 'contact'])->name('contact');

        Route::get('timetable', [FrontController::class, 'timetable'])->name('timetable');
        Route::get('timetable/{id}/show', [FrontController::class, 'timetableDetail'])->name('timetable.detail');




    });

    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('login', [AuthController::class, 'AuthLogin']);
    Route::get('register', [AuthController::class, 'register'])->name('register');
    Route::post('register', [AuthController::class, 'store']);
    Route::get('logout', [AuthController::class, 'logout']);
    Route::get('forgot-password', [AuthController::class, 'forgotpassword']);
    Route::post('forgot-password', [AuthController::class, 'PostForgotPassword']);
    Route::get('reset/{token}', [AuthController::class, 'reset']);
    Route::post('reset/{token}', [AuthController::class, 'PostReset']);
});



// Route::get('admin/dashboard', function () {
//     return view('admin.dashboard');
// })->name('admin.dashboard');



Route::group(['middleware' => ['admin', 'auth', 'SetSessionData']], function () {

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/dashboard' , [DashboardController::class,'dashboard'])->name('dashboard');
        Route::get('/admin/dashboard', [DashboardController::class, 'dashboard'])->name('admin.dashboard');
        Route::get('/user/profile', [DashboardController::class, 'profile'])->name('user.profile');
        Route::get('/user/profile_edit/{id}', [DashboardController::class, 'edit'])->name('user.profile_edit');
        Route::put('/user/profile_update/{id}', [DashboardController::class, 'update'])->name('user.profile_update');
        // Route::get('admin/user/profile_edit/{id}', [DashboardController::class, 'edit'])->name('admin.user.profile_edit');
        // Route::get('/dashboard', function () {

        //     $data['header_title'] = 'Dashboard';
        //     $classRoomsCount = ClassRoom::count();
        //     // $timetableCount = Timetable::count();
        //     $teachersCount = Teacher::count('id');
        //     return view('admin/dashboard',compact('data','classRoomsCount', 'teachersCount'));
        //     // return view('admin.dashboard');
        // })->name('dashboard');

        Route::get('admin/list', [AdminController::class, 'list'])->name('admin.list');
        Route::get('admin/add', [AdminController::class, 'add']);
        Route::post('admin/add', [AdminController::class, 'insert']);
        Route::get('admin/edit/{id}', [AdminController::class, 'edit']);
        Route::post('admin/edit/{id}', [AdminController::class, 'update']);
        Route::get('admin/delete/{id}', [AdminController::class, 'delete']);


        //change_password
        Route::get('change_password', [UserController::class, 'change_password']);
        Route::post('change_password', [UserController::class, 'update_change_password']);

        //Student
        Route::get('student/list', [StudentController::class, 'list']);
        Route::get('student/add', [StudentController::class, 'add']);
        Route::post('student/add', [StudentController::class, 'insert']);

        Route::get('timetable/welcome', function (){
            return view('admin.timetable.welcome');
        });


        Route::resource('grade', GradeController::class);

        Route::get('class_room/update_is_outstanding', [ClassRoomController::class, 'updateIsOutstanding'])->name('class_room.update_is_outstanding');
        Route::resource('class_room', ClassRoomController::class);

        Route::resource('subject_type', SubjectTypeController::class);

        Route::resource('subject', SubjectController::class);
        Route::get('teacher/loadImportForm',[TeacherController::class,'loadImportForm'])->name('teacher.loadImportForm');
        Route::post('teacher/import',[TeacherController::class,'ImportTeacher'])->name('teacher.import');
        Route::get('teacher/export', [TeacherController::class, 'ExportTeacher'])->name('teacher.export');
        Route::get('teacher/{id}/timetable', [TeacherController::class, 'timetable'])->name('teacher.timetable');
        Route::resource('teacher', TeacherController::class);
        Route::resource('user', UserController::class);

        Route::get('timetable/generate', [TimeTableController::class, 'generateTimetable'])->name('timetable.generate');
        // Route::match(['get', 'post'], 'timetable/show_popup_create',[TimeTableController::class, "showPopupCreate"])->name('timetable.showPopupCreate');
        Route::get('timetable/show_popup_create',[TimeTableController::class, "showPopupCreate"])->name('timetable.showPopupCreate');
        Route::get('timetable/{id}/show_popup_edit',[TimeTableController::class, "showPopupEdit"])->name('timetable.showPopupEdit');
        // Route::get('timetable/create_slot',[TimeTableController::class, "showPopupCreate"])->name('timetable.create_slot');
        Route::get('timetable/create_academic_year',[TimeTableController::class, "academicYearCreate"])->name('timetable.academicYearCreate');
        Route::get('timetable/grade_list', [TimeTableController::class, 'getGradeList'])->name('timetable.grade_list');
        Route::post('timetable_slot', [TimetableSlotController::class, 'store'])->name('timetable_slot.store');
        Route::put('timetable_slot/{id}/update', [TimetableSlotController::class, 'update'])->name('timetable_slot.update');
        Route::get('timetable/{id}/adjustment', [TimeTableController::class, 'adjustment'])->name('timetable.adjustment');
        Route::get('timetable/{id}/weekly_adjustment', [TimeTableController::class, 'weeklyAdjustment'])->name('timetable.weekly_adjustment');
        Route::get('timetable_slot/{id}/popup_confirm', [TimetableSlotController::class, 'popupConfirm'])->name('timetable_slot.popupConfirm');
        Route::resource('timetable', TimeTableController::class);


        Route::resource('academic_year', AcademicYearController::class);

        //time_slot
        Route::resource('time_slot', SlotTimeController::class);

        Route::resource('roles', RoleController::class);

        // settings
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {

            Route::get('/', [SettingController::class, 'index'])->name('index');
            Route::put('/save', [SettingController::class, 'save'])->name('save');

            Route::get('/general', [SettingController::class, 'general'])->name('general.index');
            Route::put('/general/save', [SettingController::class, 'generalSave'])->name('general.save');

            // language setup
            Route::group(['prefix' => 'language', 'as' => 'language.'], function () {
                Route::get('/', [LanguageController::class, 'index'])->name('index');
                Route::get('/create', [LanguageController::class, 'create'])->name('create');
                Route::post('/', [LanguageController::class, 'store'])->name('store');
                Route::get('/edit', [LanguageController::class, 'edit'])->name('edit');
                Route::put('/update', [LanguageController::class, 'update'])->name('update');
                Route::delete('delete/', [LanguageController::class, 'delete'])->name('delete');

app/Models/Grade.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Grade extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];

    protected $appends = ['subjects'];

    public function classes () {
        return $this->hasMany(ClassRoom::class);
    }
    public function getSubjectsAttribute () {
        $subjects = Subject::where('grade_id', 'LIKE', '%"'.$this->id .'"%')->get();
        return $subjects;
    }

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('orderBy', function (Builder $builder) {
            $builder->orderBy('name');
        });
    }

}

app/Http/Controllers/GradeController.php
<?php

namespace App\Http\Controllers;

use App\Helper\AppHelper;
use App\Models\Grade;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use function Termwind\render;

class GradeController extends Controller
{
    
    public function index()
    {
        if (!auth()->user()->can('grade.view')) {
            abort(403, 'Unauthorized action.');
        }
        $grades = Grade::orderBy('name', 'ASC')->paginate();

        return view('admin.grade.index', compact('grades'));
    }
    public function create()
    {
        if (!auth()->user()->can('grade.create')) {
            abort(403, 'Unauthorized action.');
        }
        return view('admin.grade.partials._create');
    }
    public function store(Request $request)
    {
        if (!auth()->user()->can('grade.create')) {
            abort(403, 'Unauthorized action.');
        }
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:grades,name',
        ], [
            'name.required' => __('Class Name is required'),
            'name.unique'   => __('This Class is already added')
        ]);

        if ($validator->errors()->count() > 0) {
            return response()->json(['errors' => AppHelper::error_processor($validator)]);
        }


        Grade::create(['name' => $request->name]);

        $table = $this->renderTable();
        $view = $table['view'];
        $total = $table['total'];

        return response()->json([
            'success' => true,
            'view' => $view,
            'data' => $request->all(),
            'total' => $total,
        ]);
    }
    public function show(Grade $grade)
    {
        //
    }

    public function edit(Grade $grade)
    {
        if (!auth()->user()->can('grade.edit')) {
            abort(403, 'Unauthorized action.');
        }

        return view('admin.grade.partials._edit', compact('grade'));
    }
    public function update(Request $request, Grade $grade)
    {
        if (!auth()->user()->can('grade.edit')) {
            abort(403, 'Unauthorized action.');
        }
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:grades,name,' . $grade->id,
        ], [
            'name.required' => __('Class Name is required'),
            'name.unique'   => __('This Class is already added')
        ]);

        if ($validator->errors()->count() > 0) {
            return response()->json(['errors' => AppHelper::error_processor($validator)]);
        }

        $grade->name = $request->name;
        $grade->save();

        $table = $this->renderTable();
        $view = $table['view'];
        $total = $table['total'];

        return response()->json([
            'view' => $view,
            'data' => $request->all(),
            'total' => $total,
        ]);

    }
    public function destroy(Grade $grade)
    {
        if (!auth()->user()->can('grade.delete')) {
            abort(403, 'Unauthorized action.');
        }
        $grade->delete();

        $table = $this->renderTable();
        $view = $table['view'];
        $total = $table['total'];
        // $grades

        return response()->json([
            'view' => $view,
            'total' => $total,
        ]);
    }

    public function renderTable () {
        $grades = Grade::orderBy('name', 'ASC')->paginate();
        $view = view('admin.grade.partials._table', compact('grades'))->render();

        return ['view' => $view, 'total' => $grades->total()];
    }
}

resources/views/admin/grade/partials/_create.blade.php
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ __('Add Grade') }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        <form action="{{ route('admin.grade.store') }}" class="submit-form" method="post">
            <div class="modal-body">
                @csrf
                <div class="form-group">
                    <label for="name">{{ __('Name') }}</label>
                    <input type="number" name="name" min="1" class="form-control">
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Close') }}</button>
                <button type="submit" class="btn btn-primary submit">{{ __('Save') }}</button>
            </div>
        </form>
    </div>
</div>

<script>
    $('.submit').click(function (e) {
        e.preventDefault();
        var data = $('.submit-form').serialize();
        console.log(data);
        $.ajax({

            type: "post",
            url: `{{ route('admin.grade.store') }}`,
            data: data,
            // dataType: "json",
            success: function (response) {
                console.log(response)
                if (response.errors) {
                    for (var i = 0; i < response.errors.length; i++) {
                        Toast.fire({
                            icon: 'error',
                            title: response.errors[i].message,
                        });
                    }
                } else {
                    Toast.fire({
                        icon: 'success',
                        title: `{{ __('Created successfully') }}`,
                        // message: ,
                    });
                    $('div.modal_form').modal('hide');
                    $('.table-wrapper').replaceWith(response.view);
                    $('.total-count').html(response.total);
                }

            }
        });
    });
</script>

resources/views/admin/grade/partials/_edit.blade.php
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ __('Edit Grade') }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        <form action="{{ route('admin.grade.update', $grade->id) }}" class="submit-form" method="post">
            <div class="modal-body">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">{{ __('Name') }}</label>
                    <input type="number" name="name" min="1" value="{{ $grade->name }}" class="form-control">
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Close') }}</button>
                <button type="submit" class="btn btn-primary submit">{{ __('Save') }}</button>
            </div>
        </form>
    </div>
</div>

<script>
    $('.submit').click(function (e) {
        e.preventDefault();
        var data = $('.submit-form').serialize();
        console.log(data);
        $.ajax({

            type: "post",
            url: `{{ route('admin.grade.update', $grade->id) }}`,
            data: data,
            // dataType: "json",
            success: function (response) {
                console.log(response);
                if (response.errors) {
                    for (var i = 0; i < response.errors.length; i++) {
                        Toast.fire({
                            icon: 'error',
                            title: response.errors[i].message,
                        });
                    }
                } else {
                    $('div.modal_form').modal('hide');
                    $('.table-wrapper').replaceWith(response.view);
                    $('.total-count').html(response.total);

                    Toast.fire({
                        icon: 'success',
                        title: `{{ __('Updated successfully') }}`
                    });
                }

            }
        });
    });
</script>

resources/views/admin/grade/partials/_table.blade.php
<div class="card-body p-0 table-wrapper">
    <table class="table">
        <thead>
            <tr>
                {{-- <th >#</th> --}}
                <th>{{ __('Name') }}</th>
                {{-- <th>Created by</th> --}}
                <th>{{ __('Created date') }}</th>
                <th>{{ __('Action') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($grades as $grade)
                <tr>
                    {{-- <td>{{$grade->id}}</td> --}}
                    <td>{{ $grade->name }}</td>
                    <td>{{ $grade->created_at->format('d M Y h:i A') }}</td>
                    <td>
                        @if (auth()->user()->can('grade.edit'))
                            <a href="#" data-href="{{ route('admin.grade.edit', $grade->id) }}"
                                data-container=".modal_form" class="btn btn-info btn-sm btn-edit">
                                <i class="fas fa-pencil-alt"></i>
                                {{ __('Edit') }}
                            </a>
                        @endif
                        @if (auth()->user()->can('grade.delete'))
                            <form action="{{ route('admin.grade.destroy', $grade->id) }}"
                                class="d-inline-block form-delete-{{ $grade->id }}">
                                @csrf
                                @method('DELETE')
                                <button type="submit" data-id="{{ $grade->id }}"
                                    data-href="{{ route('admin.grade.destroy', $grade->id) }}"
                                    class="btn btn-danger btn-sm btn-delete">
                                    <i class="fas fa-trash"></i>
                                    {{ __('Delete') }}
                                </button>
                            </form>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    {{-- <div style="padding: 10px; float: right;">

        {{ $grades->links() }}
    </div> --}}

    <div class="row">
        <div class="col-12 d-flex flex-row flex-wrap">
            <div class="row" style="width: -webkit-fill-available;">
                <div class="col-12 col-sm-6 text-center text-sm-left pl-3" style="margin-block: 20px">
                    {{ __('Showing') }} {{ $grades->firstItem() }} {{ __('to') }} {{ $grades->lastItem() }}
                    {{ __('of') }} {{ $grades->total() }} {{ __('entries') }}
                </div>
                <div class="col-12 col-sm-6 pagination-nav pr-3"> {{ $grades->links() }}</div>
            </div>
        </div>
    </div>


</div>